# Generated by Django 6.1 on 2026-08-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LossEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apid', models.IntegerField(db_index=True)),
                ('expected_sequence', models.IntegerField()),
                ('received_sequence', models.IntegerField()),
                ('lost_count', models.IntegerField()),
                ('detected_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RawPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apid', models.IntegerField(db_index=True)),
                ('sequence_count', models.IntegerField()),
                ('raw_bytes', models.BinaryField()),
                ('received_at', models.DateTimeField(db_index=True)),
                ('onboard_time', models.BigIntegerField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('snr', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='tcp', max_length=32)),
            ],
            options={
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['apid', 'sequence_count'], name='telemetry_r_apid_2eaf78_idx'), models.Index(fields=['apid', 'received_at'], name='telemetry_r_apid_7eba8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParameterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apid', models.IntegerField(db_index=True)),
                ('parameter_name', models.CharField(db_index=True, max_length=64)),
                ('raw_value', models.BigIntegerField()),
                ('engineering_value', models.FloatField(blank=True, null=True)),
                ('engineering_label', models.CharField(blank=True, max_length=64, null=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('onboard_time', models.BigIntegerField(blank=True, null=True)),
                ('raw_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='telemetry.rawpacket')),
            ],
            options={
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['parameter_name', 'received_at'], name='telemetry_p_paramet_9bb8fb_idx'), models.Index(fields=['apid', 'received_at'], name='telemetry_p_apid_aee0b7_idx')],
            },
        ),
    ]
