# Generated by Django 6.1 on 2026-08-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_flight_lossevent_flight_rawpacket_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('complete', 'complete')], default='active', max_length=16),
        ),
    ]
