"""Telemetry archive models.

Two-tier archive, as designed:

  RawPacket       - every received packet, bit-exact, the source of truth.
  ParameterSample - decoded values as a time series, config-driven (one row per
                    parameter per packet), derived from raw and regenerable.
  LossEvent       - a detected gap in a stream's sequence counter.

The parameter archive is config-driven: adding a sensor to the mission database
adds rows to the same table, never a schema change. Values are stored both raw
(the on-wire integer) and engineering (calibrated), so the archive answers both
"what did the vehicle send" and "what did it mean".
"""

from django.db import models


class RawPacket(models.Model):
    """One received packet, stored bit-exact. The source of truth.

    Everything else is derived from this and can be regenerated by re-decoding.
    Link-quality columns (rssi, snr) are nullable: they are empty for simulated
    or TCP sources and populated by a real radio.
    """

    # Identity and framing.
    apid = models.IntegerField(db_index=True)
    sequence_count = models.IntegerField()

    # The bytes exactly as received.
    raw_bytes = models.BinaryField()

    # Timing: Earth-receive time (when the ground received it) is distinct from
    # the onboard timestamp carried inside the packet. Both are recorded.
    received_at = models.DateTimeField(db_index=True)
    onboard_time = models.BigIntegerField(null=True, blank=True)

    # Link quality — populated by a real radio, null otherwise.
    rssi = models.IntegerField(null=True, blank=True)
    snr = models.FloatField(null=True, blank=True)

    # Provenance: which source produced this (e.g. "tcp", "lora", "replay").
    source = models.CharField(max_length=32, default="tcp")

    class Meta:
        indexes = [
            models.Index(fields=["apid", "sequence_count"]),
            models.Index(fields=["apid", "received_at"]),
        ]
        ordering = ["received_at"]

    def __str__(self) -> str:
        return f"RawPacket(apid={self.apid}, seq={self.sequence_count}, {len(self.raw_bytes)}B)"


class ParameterSample(models.Model):
    """One decoded parameter value from one packet. Config-driven: the set of
    parameter names comes from the mission database, not from the schema.

    Storing both raw and engineering values means recalibration can regenerate
    the engineering column from raw without re-decoding the packet, and queries
    can use whichever they need.
    """

    raw_packet = models.ForeignKey(
        RawPacket, on_delete=models.CASCADE, related_name="samples"
    )
    apid = models.IntegerField(db_index=True)
    parameter_name = models.CharField(max_length=64, db_index=True)

    # The on-wire integer value.
    raw_value = models.BigIntegerField()

    # The calibrated value. Numeric parameters use engineering_value; enumerated
    # parameters (e.g. fix quality, event code) use engineering_label.
    engineering_value = models.FloatField(null=True, blank=True)
    engineering_label = models.CharField(max_length=64, null=True, blank=True)

    # Denormalised timing for fast time-series queries without joining RawPacket.
    received_at = models.DateTimeField(db_index=True)
    onboard_time = models.BigIntegerField(null=True, blank=True)

    class Meta:
        indexes = [
            models.Index(fields=["parameter_name", "received_at"]),
            models.Index(fields=["apid", "received_at"]),
        ]
        ordering = ["received_at"]

    def __str__(self) -> str:
        shown = self.engineering_label if self.engineering_label is not None else self.engineering_value
        return f"ParameterSample({self.parameter_name}={shown})"


class LossEvent(models.Model):
    """A detected gap in a stream's per-APID sequence counter.

    Recorded when the sequence count jumps by more than one (accounting for the
    14-bit wrap at 16384), indicating one or more packets were not received.
    """

    apid = models.IntegerField(db_index=True)
    expected_sequence = models.IntegerField()
    received_sequence = models.IntegerField()
    lost_count = models.IntegerField()
    detected_at = models.DateTimeField(db_index=True)

    class Meta:
        ordering = ["detected_at"]

    def __str__(self) -> str:
        return (f"LossEvent(apid={self.apid}, expected={self.expected_sequence}, "
                f"got={self.received_sequence}, lost={self.lost_count})")
